---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: splatform/cf-ci-buildpacks
inputs:
  - name: buildpack
run:
  path: bash
  args:
    - -c
    - "cd buildpack && ./bin/check-modules-in-manifest"
