---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cfbuildpacks/ci
inputs:
  - name: buildpacks-ci
  - name: buildpack
  - name: cf-bp-space
    path: cf-space
run:
  path: /bin/true
params:
  COMPOSER_GITHUB_OAUTH_TOKEN:
  STACKS:
  CF_PASSWORD:
  RUBYGEM_MIRROR:
