---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: splatform/cf-ci-buildpacks
inputs:
  - name: buildpacks-ci
  - name: buildpack
run:
  path: /bin/true
params:
  COMPOSER_GITHUB_OAUTH_TOKEN:
  STACKS:
  CF_PASSWORD:
  RUBYGEM_MIRROR:
