---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: splatform/binary_builder_obs_opensuse
inputs:
- name: buildpacks-ci
- name: source-artifacts
run:
  path: buildpacks-ci/tasks/push-sources-to-obs/run.sh
