---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: splatform/cf-ci-buildpacks

inputs:
  - name: ci-develop

run:
  path: ci-develop/tasks/run-shellcheck/run.rb

params:
  DIRECTORY_TO_CHECK:
