---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: splatform/cf-ci-buildpacks
inputs:
  - name: buildpacks-ci
  - name: blob
outputs:
  - name: buildpack-zip
run:
  path: buildpacks-ci/tasks/build-offline-buildpack-cutlass/run.sh
