---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: splatform/cf-ci-buildpacks
inputs:
  - name: buildpacks-ci
  - name: bal-develop
run:
  path: buildpacks-ci/tasks/run-bal-specs/run.sh
