---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: splatform/cf-ci-buildpacks
inputs:
  - name: buildpacks-ci
  - name: stack-s3
  - name: version
outputs:
  - name: cflinuxfs2-archive
run:
  path: buildpacks-ci/tasks/update-rootfs-filename/run.sh
