---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: splatform/cf-ci-buildpacks

inputs:
  - name: buildpack-master
  - name: buildpack-packager
  - name: buildpacks-ci

outputs:
  - name: buildpack-artifacts

run:
  path: buildpacks-ci/tasks/package-cached-buildpack/run.sh
