---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: splatform/cf-ci-buildpacks
inputs:
  - name: binary-builder-artifacts
  - name: buildpacks-ci
run:
  path: bash
  args:
    - -cl
    - buildpacks-ci/tasks/push-binary/run.rb
