---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: splatform/cf-ci-buildpacks
inputs:
  - name: buildpacks-ci
  - name: buildpack
run:
  path: buildpacks-ci/tasks/check-tag-not-already-added/run.sh
