---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: splatform/cf-ci-buildpacks
inputs:
  - name: buildpacks-ci
  - name: stack-s3
  - name: cflinuxfs2-release
outputs:
  - name: cflinuxfs2-release-artifacts
run:
  path: buildpacks-ci/tasks/overwrite-cflinuxfs2-release/run.sh
