---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: splatform/binary_builder_obs_opensuse
    tag: latest
inputs:
  - name: binary-builder
  - name: buildpacks-ci
  - name: builds-yaml
  - name: built-yaml
outputs:
  - name: binary-builder-artifacts
  - name: builds-yaml-artifacts
run:
  path: bash
  args:
    - -cl
    - buildpacks-ci/tasks/build-binary-obs/run.rb
params:
  RUBYGEM_MIRROR:
