---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: splatform/cf-ci-buildpacks
inputs:
  - name: buildpacks-ci
  - name: resource-pools
outputs:
  - name: resource-pools-artifacts
run:
  path: buildpacks-ci/tasks/unclaim-bosh-lite-resource/run.sh
