---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: splatform/cf-ci-buildpacks
inputs:
  - name: release-artifacts
outputs:
  - name: release-commit
run:
  path: bash
  args:
    - "-c"
    - 'cd release-artifacts && git rev-list HEAD -n1 > ../release-commit/sha'
