---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: splatform/cf-ci-buildpacks

inputs:
  - name: buildpack
  - name: buildpacks-ci
  - name: pivotal-buildpacks-cached
  - name: pivnet-buildpack-metadata
  - name: buildpack-artifacts

outputs:
  - name: pivnet-buildpack-metadata-artifacts

run:
  path: bash
  args:
    - -cl
    - buildpacks-ci/tasks/write-buildpack-pivnet-metadata/run.rb
